version: "3.9"
services:
  postgres:
    container_name: db
    image: db
    build: ./db/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - 5432
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
    image: api
    build: ./api/.
    ports:
      - 3000:8000
    networks:
      - db
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/main
    

networks:
  db:
    name: db
  
