version: "3.9"
services:
  postgres:
    container_name: db
    image: db
    build: ./db/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    command: postgres -c listen_addresses='*'
    ports:
      - 5434:5432
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 4

networks:
  db:
    name: db
  
