version: "3.9"
services:
  postgres:
    container_name: db
    image: db
    build: ./db/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - 5432
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
    image: api
    build: ./api/.
    environment:
      POSTGRES_URL: postgresql://api:1234@db:5432/main
    networks:
      - db
    ports: 
      - 3000:8000
  frontend:
    container_name: frontend
    build: ./frontend/.
    environment:
      API_URL: api:3000
    networks:
      - db
    ports: 
      - 8000:3000

networks:
  db:
    name: db
  
