version: "3.8"
services:
  postgres:
    container_name: db
    image: localhost:5000/db
    build: ./db/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - 5432
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  fastapi:
    container_name: api
    image: localhost:5000/api
    build: ./api/.
    ports:
      - 8000
    networks:
      - db
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/main
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  frontend:
    container_name: frontend
    image: localhost:5000/frontend
    build: ./frontend/.
    environment:
      API_URL: api:3000
    networks:
      - db
    ports:
      - 8000:3000
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  db:
    name: db
  
