---
- hosts: all
  gather_facts: true
  become: false
  vars_files:
    - group_vars/main.yml
  
  tasks:
  - name: Clone a github repository
    git:
      repo: "https://github.com/{{  git_repo  }}"
      dest: /home/user/basel_viz
      clone: yes
      update: yes

  - name: Adding api .env
    copy:
      src: ../../api/api/.env
      dest: /home/user/basel_viz/api/api/.env

  - name: Adding frontend .env
    copy:
      src: ../../frontend/.env
      dest: /home/user/basel_viz/frontend/.env

  - name: building images
    shell: cd basel_viz && docker compose build --no-cache  
        
  - name: pushing images
    shell: cd basel_viz && docker compose push

  - name: deploying stack
    shell: |
      cd basel_viz && docker stack deploy --prune --resolve-image always -c docker-compose.yml app 